on:
  push:
    tags: ['v[0-9]+.[0-9]+.*']

jobs:
  release:
    runs-on: codeberg-tiny
    steps:
      - name: checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - uses: actions/git-pages@v2
        with:
          # This workflow will only work correctly in https://codeberg.org/username/reponame.git !
          # Adjust the site name to match your username and repository name.
          # To publish to the index site, https://username.codeberg.page/, name your repository
          # either `username.codeberg.page` or `pages`.
          site: https://noo.codeberg.page/dotfiles/
          token: ${{ forge.token }}
          source: _site/
